# Khai báo phiên bản của docker compose file
# Để format file
version: '3'
services:
  #PHP
  php-fpm:
    # Đặt tên cho container chứa source code
    container_name: laravel_8
    # Đường dẫn tới folder chứa config build dự án laravel
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../../../demoLaravel8:/var/www
    # Setting network để các container giao tiếp với nhau
    networks:
      - app-networks
  #NGINX
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Tham chiếu file config nginx của mình vào môi trường ảo nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Tham chiếu source của mình vào trong môi trường ảo docker
      - ../../../demoLaravel8:/var/www
    working_dir: /var/www
    ports:
      - 8888:80
    # Setting network để các container giao tiếp với nhau
    networks:
      - app-networks
  #MYSQL
  mysql:
    # Đặt tên cho container chứa Mysql
    container_name: db-laravel-8
    # Đường dẫn tới folder chứa config build Mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    # Config port của Mysql
    ports:
      - 3333:3306
    # Setup tên database và password cho root user
    environment:
      MYSQL_DATABASE: db_laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    # Set bộ ký tự cho dữ liệu
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # Tham chiếu DB đã build khi start lại docker
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    # Setting network để các container giao tiếp với nhau
    networks:
      - app-networks
  phpmyadmin:
    container_name: laravel_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db-laravel-8
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8181:80
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge